### ISSUE TITLE
Change button color throughout the application

### ISSUE THREAD

**Issue by jerrythimothyj** [jerrythimothyj/moneymanager#108]

**Comment by jerrythimothyj** [comment]
git branch feature/buttoncolors
git checkout feature/buttoncolors

Work

git status
git add -A
git commit -m "#108: Colors changed"
git push origin feature/buttoncolors

Create pull request
Assign Jerry

**Comment by jerrythimothyj** [comment]
Colors should match the dark green in bigjapps.com

#009444

...

**Comment by maniadelasoft** [comment]
color.css
.btn-custom {
    background-color: #009444;
    color: #ffffff;
}

.btn-custom:hover {
    background-color:#39b54a;
    color: #ffffff;
}
