### ISSUE TITLE
ScratchPad Type Text Editor for Expenses

### ISSUE THREAD

**Issue by jerrythimothyj** [jerrythimothyj/moneymanager#2]

**Comment by nirajdewangan** [comment]
1. Date combo box initialize with current date.
2. Generate new record on key down or key press.
3. When delete option is clicked remove the record

**Comment by jerrythimothyj** [comment]
@nirajdewangan 

expensemanager/client/views/pages/expenses.php should only have <expenses-grid></expenses-grid>

expensemanager/client/views/components/expensesGrid.php should have all the design.

Follow this code as reference for creating dynamic rows:
https://codepen.io/calendee/pen/buCHf

**Comment by jerrythimothyj** [comment]
API is ready @nirajdewangan

**Comment by jerrythimothyj** [comment]
The payload should be:

```
{  
    "date":"2016/09/08",
    "expenses":[  
        {  
            "expenseType":3,
            "spendingType":2,
            "amount":10.00
        },
        {  
            "expenseType":2,
            "spendingType":1,
            "amount":98.00
        }
    ]
}
```

**Comment by jerrythimothyj** [comment]
```
<chosen-date></chosen-date>
<expense-records></expense-records>

```
Create the above 2 directives on expense.html and paste the respective codes on those directives html.
