### ISSUE TITLE
Create Login Panel

### ISSUE THREAD

**Issue by hemavathimk** [jerrythimothyj/moneymanager#35]

**Comment by jerrythimothyj** [comment]
@gitraghavan 

expensemanager/client/views/pages/login.php should only contain <login-panel></login-panel>

expensemanager/client/views/components/loginPanel.php should only contain actual design.

Follow the same steps for Registration Page and Forgot Password Page.

Take reference from the sample programs ( https://github.com/jerrythimothyj/UIDevelopment ) to create a form.

**Comment by nirajdewangan** [comment]
`.run(function ($state,$rootScope) {
       $rootScope.$state = $state;
    })`

**Comment by nirajdewangan** [comment]
`<li data-ng-if="$state.current.name != 'register' && $state.current.name != 'login' && $state.current.name != 'forgotPassword'" class="active" ><a ui-sref="dashboard">Dashboard</a></li>`
