### ISSUE TITLE
Test Expense Category with Dummy Data on Dashboard

### ISSUE THREAD

**Issue by jerrythimothyj** [jerrythimothyj/moneymanager#38]

**Comment by mangeshrao** [comment]
Display dummy data on dashboard

**Comment by jerrythimothyj** [comment]
@mangeshrao 

Please use the values below:

[ { "size" : "1",
    "name" : "food"
  },
  { "size" : "2",
    "name" : "snacks"
  },
  { "size" : "3",
    "name" : "clothing"
  },
  { "size" : "4",
    "name" : "entertainment"
  },
  { "size" : "5",
    "name" : "electricity"
  },
  { "size" : "6",
    "name" : "water"
  },
  { "size" : "7",
    "name" : "wage"
  },
  { "size" : "8",
    "name" : "travel"
  },
  { "size" : "9",
    "name" : "construction"
  },
  { "size" : "10",
    "name" : "others"
  },
  { "size" : "11",
    "name" : "groceries"
  },
  { "size" : "12",
    "name" : "phone"
  },
  { "size" : "13",
    "name" : "emi"
  },
  { "size" : "14",
    "name" : "debt"
  },
  { "size" : "15",
    "name" : "toys"
  },
  { "size" : "16",
    "name" : "furnitures"
  },
  { "size" : "17",
    "name" : "household"
  },
  { "size" : "18",
    "name" : "rent"
  },
  { "size" : "19",
    "name" : "donation"
  },
  { "size" : "20",
    "name" : "pets"
  },
  { "size" : "21",
    "name" : "tv"
  },
  { "size" : "22",
    "name" : "internet"
  },
  { "size" : "23",
    "name" : "hobby"
  },
  { "size" : "24",
    "name" : "jewels"
  },
  { "size" : "25",
    "name" : "electronics"
  },
  { "size" : "26",
    "name" : "electricals"
  },
  { "size" : "27",
    "name" : "baby"
  },
  { "size" : "28",
    "name" : "medication"
  },
  { "size" : "29",
    "name" : "trainings"
  },
  { "size" : "30",
    "name" : "grooming"
  },
  { "size" : "31",
    "name" : "moving"
  },
  { "size" : "32",
    "name" : "bank"
  },
  { "size" : "33",
    "name" : "creditcard"
  },
  { "size" : "34",
    "name" : "gifts"
  },
  { "size" : "35",
    "name" : "debitcard"
  },
  { "size" : "36",
    "name" : "othercards"
  },
  { "size" : "37",
    "name" : "photography"
  },
  { "size" : "38",
    "name" : "decoration"
  },
  { "size" : "39",
    "name" : "painting"
  },
  { "size" : "40",
    "name" : "labor"
  },
  { "size" : "41",
    "name" : "service"
  },
  { "size" : "42",
    "name" : "sales"
  },
  { "size" : "43",
    "name" : "vehicle"
  },
  { "size" : "44",
    "name" : "advertising"
  },
  { "size" : "45",
    "name" : "alcohol"
  },
  { "size" : "46",
    "name" : "cylindergases"
  },
  { "size" : "47",
    "name" : "hospitality"
  },
  { "size" : "48",
    "name" : "gasoline"
  },
  { "size" : "49",
    "name" : "forms"
  },
  { "size" : "50",
    "name" : "postage"
  },
  { "size" : "51",
    "name" : "safety"
  },
  { "size" : "52",
    "name" : "tax"
  },
  { "size" : "53",
    "name" : "meetings"
  }
]


Put the above values in the below file:
expensemanager/client/js/controllers/bubbleChart.js
