### ISSUE TITLE
Create Logout

### ISSUE THREAD

**Issue by jerrythimothyj** [jerrythimothyj/moneymanager#39]

**Comment by GirishKona** [comment]
On click of Guest
 A Drop down list is dropped down (UI BootStrap ) with following options
   Settings
   Profile
   Logout

Clicking on Logout should navigate to Login Page

**Comment by jerrythimothyj** [comment]
<img width="1302" alt="screen shot 2016-08-28 at 8 16 11 pm" src="https://cloud.githubusercontent.com/assets/16850946/18034510/7c004604-6d5c-11e6-83d8-1e5f8ecc6044.png">

@GirishKona Please follow the above procedures to create logout design.

expensemanager/client/views/components/

Create a file ( profilePopup.php ) in the above path.
